/**
 * TLS 测试用的证书材料。
 *
 * 现造不出来 —— Node 标准库只能**解析** X.509，不能签发，所以这几份是用
 * openssl 预先生成好钉在这里的（EC P-256，PEM 短）。自签、有效期到 2126 年，
 * 私钥是公开的，**只能用于单测**，任何环境都不该出现。
 *
 * 文件名以 `.fixtures.ts` 结尾是刻意的：tsconfig 把这个后缀排除在编译之外，
 * 这几把私钥不会跟着进 dist、更不会进镜像 —— 否则每次安全扫描都要来问一遍。
 *
 * 三份材料的关系：`CLIENT_CERT` 由 `CA_CERT` 签发、与 `CLIENT_KEY` 配对；
 * `OTHER_KEY` 谁也不配，专门用来验「证书和私钥不是一对」那条校验。
 */

/** 自签 CA */
export const CA_CERT = `-----BEGIN CERTIFICATE-----
MIIBxDCCAWugAwIBAgIUUnI2gPM2LkEwL9teKOqpkG+F42wwCgYIKoZIzj0EAwIw
NzEgMB4GA1UEAwwXVGhpbmdMaW5rcyBFZGdlIFRlc3QgQ0ExEzARBgNVBAoMClRo
aW5nTGlua3MwIBcNMjYwODI3MTIwMzE0WhgPMjEyNjA4MDMxMjAzMTRaMDcxIDAe
BgNVBAMMF1RoaW5nTGlua3MgRWRnZSBUZXN0IENBMRMwEQYDVQQKDApUaGluZ0xp
bmtzMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEf4tr6I/v0GCJCGH4+ge8AGNK
XMIsJ3Ov7DpTt0wqO18mmy7oeya21CIDlO1H92Qjo68P/AaxGWH1APrREOP0+aNT
MFEwHQYDVR0OBBYEFK6Tj5ZF7I2JhyBk4KK1fy+++46QMB8GA1UdIwQYMBaAFK6T
j5ZF7I2JhyBk4KK1fy+++46QMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwID
RwAwRAIgWNH6hq3VaECPzb2fJZDcWZEepB5Ny5UqBS4mt1SkWTMCIHPWLxND6WBB
bA5fRyTr+RrTxzS0nnLJ++h1vi9PGauC
-----END CERTIFICATE-----
`;

/** 由上面的 CA 签发的客户端证书，CN=edge-gw-01 */
export const CLIENT_CERT = `-----BEGIN CERTIFICATE-----
MIIBqDCCAU2gAwIBAgIUfx+5Q1Aa7wBcemVAx8RwbuwS6cgwCgYIKoZIzj0EAwIw
NzEgMB4GA1UEAwwXVGhpbmdMaW5rcyBFZGdlIFRlc3QgQ0ExEzARBgNVBAoMClRo
aW5nTGlua3MwIBcNMjYwODI3MTIwMzE0WhgPMjEyNjA4MDMxMjAzMTRaMCoxEzAR
BgNVBAMMCmVkZ2UtZ3ctMDExEzARBgNVBAoMClRoaW5nTGlua3MwWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAAQG8jVJSaqRqo3DDv8jCN1Imt8/qunw1c0pt2t1KuIh
okc6S/5eznYOjVsS5iNnGX4M9TxHsqRXmEufsFgrmtmVo0IwQDAdBgNVHQ4EFgQU
A6MQtB9RMZ+S5vDWvrtYcjTsF8owHwYDVR0jBBgwFoAUrpOPlkXsjYmHIGTgorV/
L777jpAwCgYIKoZIzj0EAwIDSQAwRgIhALsodPLn5f0IkX91rgY+lV9evHOP+G8p
zNVnlQOUc+zhAiEAv3Y67CFgu4Q8QZMYLFGFX+IPU3E/mK+TC/Dpsvl7UgU=
-----END CERTIFICATE-----
`;

/** 与 CLIENT_CERT 配对的私钥（PKCS#8 明文） */
export const CLIENT_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg1Wbg5p7ZtqlNceYh
G3DYQvKU5NVEFR42AT0tk5G6Go2hRANCAAQG8jVJSaqRqo3DDv8jCN1Imt8/qunw
1c0pt2t1KuIhokc6S/5eznYOjVsS5iNnGX4M9TxHsqRXmEufsFgrmtmV
-----END PRIVATE KEY-----
`;

/** 一把无关的私钥。与 CLIENT_CERT 不配对 */
export const OTHER_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgk0IFS8xYQuyVC8RE
h8WzCLhJS6xkeMJOS3c+C2hzIEGhRANCAASLsM2PqSA09dTH0XoeHw+XOz2PZ9jI
Off4yEewwViZ9peaRMV9/iCGdDdMqQ2iC4oJxSHCAv8TSMnszcqm2fLP
-----END PRIVATE KEY-----
`;

/** 2021 年就过期的自签证书，用来验「过期只提示、不拦保存」 */
export const EXPIRED_CERT = `-----BEGIN CERTIFICATE-----
MIIBkjCCATegAwIBAgIUEQphwpBrFSapIiY4NND/2S43XUIwCgYIKoZIzj0EAwIw
HjEcMBoGA1UEAwwTZXhwaXJlZC5leGFtcGxlLmNvbTAeFw0yMDAxMDEwMDAwMDBa
Fw0yMTAxMDEwMDAwMDBaMB4xHDAaBgNVBAMME2V4cGlyZWQuZXhhbXBsZS5jb20w
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASqm6bUbWFAA15rqC/v2xUYB5xPy2SA
0G14PeONR/qPKw72RhXNwR71DGXNKO2ydHzrMBuAOEmQGl0eVyhuHjn+o1MwUTAd
BgNVHQ4EFgQUVEXipnR9wp63ShwgtMe7WxNNxpswHwYDVR0jBBgwFoAUVEXipnR9
wp63ShwgtMe7WxNNxpswDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNJADBG
AiEA/6BCfCzfcFlr9RJbI9WVIWjbhhuHx6GtDMp3yeyfafECIQCdlDUP62q9JFP1
qod8aBPr/utsGzb3bwFvkzqsq4OcDw==
-----END CERTIFICATE-----
`;
